In [3]:
#import needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Don't wrap repr(DataFrame) across additional lines
pd.set_option("display.expand_frame_repr", False)

# Set max rows displayed in output to 25
pd.set_option("display.max_rows", 25)

In [6]:
#question1

#extends a list
A = [1,2,3,4,5,6]
B = [13,21,34]
A.extend(B)
A_B = A
print(A_B)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


In [38]:
#question2

#to create an identity matrix
print(np.array([[1,0,0],[0,1,0], [0,0,1]]))
print(np.identity(3))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#loads the dataset from the link
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
fuel_data = pd.read_csv("fuel_data.csv", error_bad_lines=False)


#gives information about the dataset
fuel_data.describe(include="all")

Unnamed: 0                record_id  utility_id_ferc1   report_year plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu
count   29523.000000                    29523      29523.000000  29523.000000            29523               29523     29343     2.952300e+04         29523.000000               29523.000000                  2.952300e+04         29523.000000
unique           NaN                    29523               NaN           NaN             2315                   6         9              NaN                  NaN                        NaN                           NaN                  NaN
top              NaN  f1_fuel_2010_12_127_0_5               NaN           NaN        big stone                 gas       mcf              NaN                  NaN                        NaN                           NaN                  NaN
freq             NaN                        1               NaN           NaN              156               11486     11354              NaN                  NaN                        NaN                           NaN                  NaN
mean    14761.000000                      NaN        118.601836   2005.806050              NaN                 NaN       NaN     2.622119e+06             8.492111                 208.649031                  9.175704e+02            19.304354
std      8522.700335                      NaN         74.178353      7.025483              NaN                 NaN       NaN     9.118004e+06            10.600220                2854.490090                  6.877593e+04          2091.540939
min         0.000000                      NaN          1.000000   1994.000000              NaN                 NaN       NaN     1.000000e+00             0.000001                -276.080000                 -8.749370e+02           -41.501000
25%      7380.500000                      NaN         55.000000   2000.000000              NaN                 NaN       NaN     1.381700e+04             1.024000                   5.207000                  3.778500e+00             1.940000
50%     14761.000000                      NaN        122.000000   2006.000000              NaN                 NaN       NaN     2.533220e+05             5.762694                  26.000000                  1.737100e+01             4.127000
75%     22141.500000                      NaN        176.000000   2012.000000              NaN                 NaN       NaN     1.424034e+06            17.006000                  47.113000                  4.213700e+01             7.745000
max     29522.000000                      NaN        514.000000   2018.000000              NaN                 NaN       NaN     5.558942e+08           341.260000              139358.000000                  7.964521e+06        359278.000000

In [10]:
#saves the dataframe to a csv file
fuel_data.to_csv("fuel_data.csv")

In [11]:
#prints out the first five rows
fuel_data.head()

Unnamed: 0               record_id  utility_id_ferc1  report_year      plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu
0           0   f1_fuel_1994_12_1_0_7                 1         1994              rockport                coal       ton        5377489.0               16.590                      18.59                         18.53                1.121
1           1  f1_fuel_1994_12_1_0_10                 1         1994  rockport total plant                coal       ton       10486945.0               16.592                      18.58                         18.53                1.120
2           2   f1_fuel_1994_12_2_0_1                 2         1994                gorgas                coal       ton        2978683.0               24.130                      39.72                         38.12                1.650
3           3   f1_fuel_1994_12_2_0_7                 2         1994                 barry                coal       ton        3739484.0               23.950                      47.21                         45.99                1.970
4           4  f1_fuel_1994_12_2_0_10                 2         1994             chickasaw                 gas       mcf          40533.0                1.000                       2.77                          2.77                2.570

In [12]:
#drops the Unamed: 0 axis
fuel_data.drop("Unnamed: 0", axis=1, inplace=True)


Index(['record_id', 'utility_id_ferc1', 'report_year', 'plant_name_ferc1',
       'fuel_type_code_pudl', 'fuel_unit', 'fuel_qty_burned',
       'fuel_mmbtu_per_unit', 'fuel_cost_per_unit_burned',
       'fuel_cost_per_unit_delivered', 'fuel_cost_per_mmbtu'],
      dtype='object')

In [13]:
#checks for missng rows
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [41]:
#question3

#checks for mean of fuel cost per unit burned
fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [18]:
#question4
standard_dev = np.std(fuel_data["fuel_mmbtu_per_unit"])
print(standard_dev)
percentile_75 = np.percentile(fuel_data["fuel_mmbtu_per_unit"], 75)
print(percentile_75)

10.600040781504145
17.006


In [20]:
#question5

import numpy as np
from scipy.stats import kurtosis
from scipy.stats import skew
skewness = skew(fuel_data["fuel_qty_burned"])
print(skewness)
kurt = kurtosis(fuel_data["fuel_qty_burned"])
print(kurt)

15.850690077422112
651.2589365474387


In [24]:
#question6

(180 / len(fuel_data)) * 100

0.609694136774718

In [31]:
#question7

#calculates the correlation for fuel cost per unit burned
fuel_data.corr()["fuel_cost_per_unit_burned"]

utility_id_ferc1               -0.037863
report_year                     0.013599
fuel_qty_burned                -0.018535
fuel_mmbtu_per_unit            -0.010034
fuel_cost_per_unit_burned       1.000000
fuel_cost_per_unit_delivered    0.011007
fuel_cost_per_mmbtu            -0.000437
Name: fuel_cost_per_unit_burned, dtype: float64

In [32]:
#question10
#calculates the year with the highest fuel cost per unit delivered

fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64